version: '3.9'

services:
    db:
        container_name: novusdb
        image: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis
        volumes: ["redis-db:/data"]

volumes:
    redis-db:
    pgdata: {}
